HMH_CLIENT_API_KEY = "75b5cc58a5cdc0a583f91301cefedf0c"
CLIENT_ID = "ef5f7a03-58e8-48d7-a38a-abbd2696bdb6.hmhco.com"

BASE_URL = "http://sandbox.api.hmhco.com"

ACCESS_TOKEN_URL = "/v1/sample_token"

V1_STUDENT_INFO = "/v1/students"
V1_SECTION_INFO = "/v1/sections"
V1_SCHOOLS_INFO = "/v1/schools"
V1_STAFF_SECTION_ASSOCIATIONS_INFO = "/v1/staffSectionAssociations"
V1_STAFF_PERSONS_ASSIGNMENTS_INFO = "/v1/staffPersonAssignments"
V1_STUDENT_SECTION_ASSOCIATIONS_INFO = "/v1/studentSectionAssociations"
V1_STUDENT_SCHOOL_ASSOCIATIONS_INFO = "/v1/studentSchoolAssociations"
V1_STAFF_PERSONS_INFO = "/v1/staffPersons"
V1_ORGANIZATION_ORGANIZATION_ASSOCIATIONS_INFO = "/v1/organizationOrganizationAssociations"
V1_ASSIGNMENTS_INFO_URI = "/v1/assignments"
V1_ASSIGNMENT_SUBMISSIONS_INFO_URI = "/v1/assignmentSubmissions"
V1_DOCUMENTS_INFO_URI = "/v1/documents"
V1_TAGS_INFO_URI = "/v1/tags"
